[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]

solc_version = "0.8.28"
evm_version = "cancun"
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
